<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use Ramsey\Uuid\Uuid;

class Behaviors extends Model
{
    use HasFactory;

    protected $table        = "culture_behaviors";

    protected $fillable     = [
        'beh_id',
        'uuid',
        'beh_sequence',
        'beh_name',
        'beh_did_you',
        'beh_did_supervisor',
        'beh_takeaways',
        'beh_definition',
        'created_by',
        'updated_by'
        ];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        /* When Creating the Data. */
        static::creating(function ($model) {

            $model->uuid = Uuid::uuid4();
            $model->created_by = Auth::user()->id;
        });

        /* When Updating the Data.*/
        static::updating(function ($model) {

            if (!$model->isDirty('updated_by')) {
                $model->updated_by = auth()->user()->id;
            }
        });
    }
}
