<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

class Difficulties extends Model
{
    use HasFactory;

    protected $table    = "culture_difficulties";

    protected $fillable = ['dif_id', 'dif_description', 'created_by', 'updated_by', 'deleted_by'];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        /* When Creating the Data. */
        static::creating(function ($model){

            $model->created_by   = Auth::user()->id;
        });

        /* When Updating the Data.*/
        static::updating(function ($model){

            if (!$model->isDirty('updated_by')) {
                $model->updated_by = auth()->user()->id;
            }
        });
    }
}
