<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use Ramsey\Uuid\Uuid;

class Lessons extends Model
{
    use HasFactory;

    protected $table    = 'culture_lessons';

    protected $fillable = [
        'les_id',
        'uuid',
        'company_id',
        'value_id',
        'behavior_id',
        'les_title',
        'les_minutes_to_complete',
        'difficulty_id',
        'les_is_visible',
        'created_by',
        'updated_by'];


    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        /* When Createing the Data. */
        static::creating(function ($model){

            $model->uuid         = Uuid::uuid4();
            $model->created_by   = Auth::user()->id;
        });

        /* When Updating the Data.*/
        static::updating(function ($model){

            if (!$model->isDirty('updated_by')) {
                $model->updated_by = auth()->user()->id;
            }
        });
    }
}
