<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use Ramsey\Uuid\Uuid;

class ModuleSections extends Model
{
    use HasFactory;

    protected $table    = "module_sections";

    public $timestamps  = true;

    protected $fillable =   ['sec_id', 'uuid', 'sec_sequence', 'mod_id', 'sec_name', 'sec_description', 'is_active', 'created_by', 'updated_by'];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        /* When Createing the Data. */
        static::creating(function ($model){

            $model->uuid         = Uuid::uuid4();
            $model->created_by   = Auth::user()->id;
        });

        /* When Updating the Data.*/
        static::updating(function ($model){

            if (!$model->isDirty('updated_by')) {
                $model->updated_by = auth()->user()->id;
            }
        });
    }
}
